using System;
using System.Collections.Generic;
using StiebelEltronApiServer.Extensions;
using StiebelEltronApiServer.Models;

namespace StiebelEltronApiServer.Services {
    public class StatisticsService : IStatisticsService {
        public HeatPumpDataPerPeriod GetHeatPumpDataPerPeriod (IEnumerable<HeatPumpDatum> heatPumpData, int year, string periodKind, int periodNumber) {
            var now = DateTime.UtcNow;
            return new HeatPumpDataPerPeriod () {
                ReturnTemperatureMin = heatPumpData.GetMinForMetric (h => h.ReturnTemperature),
                    ReturnTemperatureMax = heatPumpData.GetMaxForMetric (h => h.ReturnTemperature),
                    ReturnTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.ReturnTemperature),
                    InletTemperatureMin = heatPumpData.GetMinForMetric (h => h.InletTemperature),
                    InletTemperatureMax = heatPumpData.GetMaxForMetric (h => h.InletTemperature),
                    InletTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.InletTemperature),
                    AntiFreezeTemperatureMin = heatPumpData.GetMinForMetric (h => h.AntiFreezeTemperature),
                    AntiFreezeTemperatureMax = heatPumpData.GetMaxForMetric (h => h.AntiFreezeTemperature),
                    AntiFreezeTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.AntiFreezeTemperature),
                    OutdoorTemperatureMin = heatPumpData.GetMinForMetric (h => h.OutdoorTemperature),
                    OutdoorTemperatureMax = heatPumpData.GetMaxForMetric (h => h.OutdoorTemperature),
                    OutdoorTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.OutdoorTemperature),
                    ExhaustAirTemperatureMin = heatPumpData.GetMinForMetric (h => h.ExhaustAirTemperature),
                    ExhaustAirTemperatureMax = heatPumpData.GetMaxForMetric (h => h.ExhaustAirTemperature),
                    ExhaustAirTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.ExhaustAirTemperature),
                    EvaporatorTemperatureMin = heatPumpData.GetMinForMetric (h => h.EvaporatorTemperature),
                    EvaporatorTemperatureMax = heatPumpData.GetMaxForMetric (h => h.EvaporatorTemperature),
                    EvaporatorTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.EvaporatorTemperature),
                    TotalPowerConsumptionStart = heatPumpData.GetStartForMetric (h => h.TotalPowerConsumption),
                    TotalPowerConsumptionEnd = heatPumpData.GetEndForMetric (h => h.TotalPowerConsumption),
                    TotalPowerConsumptionDelta = heatPumpData.GetDeltaForMetric (h => h.TotalPowerConsumption),
                    CompressorInletTemperatureMin = heatPumpData.GetMinForMetric (h => h.CompressorInletTemperature),
                    CompressorInletTemperatureMax = heatPumpData.GetMaxForMetric (h => h.CompressorInletTemperature),
                    CompressorInletTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.CompressorInletTemperature),
                    IntermediateInjectionTemperatureMin = heatPumpData.GetMinForMetric (h => h.IntermediateInjectionTemperature),
                    IntermediateInjectionTemperatureMax = heatPumpData.GetMaxForMetric (h => h.IntermediateInjectionTemperature),
                    IntermediateInjectionTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.IntermediateInjectionTemperature),
                    HotGasTemperatureMin = heatPumpData.GetMinForMetric (h => h.HotGasTemperature),
                    HotGasTemperatureMax = heatPumpData.GetMaxForMetric (h => h.HotGasTemperature),
                    HotGasTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.HotGasTemperature),
                    CondenserTemperatureMin = heatPumpData.GetMinForMetric (h => h.CondenserTemperature),
                    CondenserTemperatureMax = heatPumpData.GetMaxForMetric (h => h.CondenserTemperature),
                    CondenserTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.CondenserTemperature),
                    OilSumpTemperatureMin = heatPumpData.GetMinForMetric (h => h.OilSumpTemperature),
                    OilSumpTemperatureMax = heatPumpData.GetMaxForMetric (h => h.OilSumpTemperature),
                    OilSumpTemperatureAverage = heatPumpData.GetAverageForMetric (h => h.OilSumpTemperature),
                    LowPressureMin = heatPumpData.GetMinForMetric (h => h.LowPressure),
                    LowPressureMax = heatPumpData.GetMaxForMetric (h => h.LowPressure),
                    LowPressureAverage = heatPumpData.GetAverageForMetric (h => h.LowPressure),
                    PressureMediumMin = heatPumpData.GetMinForMetric (h => h.PressureMedium),
                    PressureMediumMax = heatPumpData.GetMaxForMetric (h => h.PressureMedium),
                    PressureMediumAverage = heatPumpData.GetAverageForMetric (h => h.PressureMedium),
                    HighPressureMin = heatPumpData.GetMinForMetric (h => h.HighPressure),
                    HighPressureMax = heatPumpData.GetMaxForMetric (h => h.HighPressure),
                    HighPressureAverage = heatPumpData.GetAverageForMetric (h => h.HighPressure),
                    WaterVolumeCurrentMin = heatPumpData.GetMinForMetric (h => h.WaterVolumeCurrent),
                    WaterVolumeCurrentMax = heatPumpData.GetMaxForMetric (h => h.WaterVolumeCurrent),
                    WaterVolumeCurrentAverage = heatPumpData.GetAverageForMetric (h => h.WaterVolumeCurrent),
                    VoltageInverterMin = heatPumpData.GetMinForMetric (h => h.VoltageInverter),
                    VoltageInverterMax = heatPumpData.GetMaxForMetric (h => h.VoltageInverter),
                    VoltageInverterAverage = heatPumpData.GetAverageForMetric (h => h.VoltageInverter),
                    ActualSpeedDensifierMin = heatPumpData.GetMinForMetric (h => h.ActualSpeedDensifier),
                    ActualSpeedDensifierMax = heatPumpData.GetMaxForMetric (h => h.ActualSpeedDensifier),
                    ActualSpeedDensifierAverage = heatPumpData.GetAverageForMetric (h => h.ActualSpeedDensifier),
                    SettingSpeedCompressedMin = heatPumpData.GetMinForMetric (h => h.SettingSpeedCompressed),
                    SettingSpeedCompressedMax = heatPumpData.GetMaxForMetric (h => h.SettingSpeedCompressed),
                    SettingSpeedCompressedAverage = heatPumpData.GetAverageForMetric (h => h.SettingSpeedCompressed),
                    FanPowerRelMin = heatPumpData.GetMinForMetric (h => h.FanPowerRel),
                    FanPowerRelMax = heatPumpData.GetMaxForMetric (h => h.FanPowerRel),
                    FanPowerRelAverage = heatPumpData.GetAverageForMetric (h => h.FanPowerRel),
                    VaporizerHeatQuantityHeatingDayStart = heatPumpData.GetStartForMetric (h => h.VaporizerHeatQuantityHeatingDay),
                    VaporizerHeatQuantityHeatingDayEnd = heatPumpData.GetEndForMetric (h => h.VaporizerHeatQuantityHeatingDay),
                    VaporizerHeatQuantityHeatingDayDelta = heatPumpData.GetDeltaForMetric (h => h.VaporizerHeatQuantityHeatingDay),
                    VaporizerHeatQuantityHeatingTotalStart = heatPumpData.GetStartForMetric (h => h.VaporizerHeatQuantityHeatingTotal),
                    VaporizerHeatQuantityHeatingTotalEnd = heatPumpData.GetEndForMetric (h => h.VaporizerHeatQuantityHeatingTotal),
                    VaporizerHeatQuantityHeatingTotalDelta = heatPumpData.GetDeltaForMetric (h => h.VaporizerHeatQuantityHeatingTotal),
                    VaporizerHeatQuantityHotWaterDayStart = heatPumpData.GetStartForMetric (h => h.VaporizerHeatQuantityHotWaterDay),
                    VaporizerHeatQuantityHotWaterDayEnd = heatPumpData.GetEndForMetric (h => h.VaporizerHeatQuantityHotWaterDay),
                    VaporizerHeatQuantityHotWaterDayDelta = heatPumpData.GetDeltaForMetric (h => h.VaporizerHeatQuantityHotWaterDay),
                    VaporizerHeatQuantityHotWaterTotalStart = heatPumpData.GetStartForMetric (h => h.VaporizerHeatQuantityHotWaterTotal),
                    VaporizerHeatQuantityHotWaterTotalEnd = heatPumpData.GetEndForMetric (h => h.VaporizerHeatQuantityHotWaterTotal),
                    VaporizerHeatQuantityHotWaterTotalDelta = heatPumpData.GetDeltaForMetric (h => h.VaporizerHeatQuantityHotWaterTotal),
                    ReheatingStagesHeatQuantityHeatingSumStart = heatPumpData.GetStartForMetric (h => h.ReheatingStagesHeatQuantityHeatingSum),
                    ReheatingStagesHeatQuantityHeatingSumEnd = heatPumpData.GetEndForMetric (h => h.ReheatingStagesHeatQuantityHeatingSum),
                    ReheatingStagesHeatQuantityHeatingSumDelta = heatPumpData.GetDeltaForMetric (h => h.ReheatingStagesHeatQuantityHeatingSum),
                    ReheatingStagesHeatQuantityHotWaterTotalStart = heatPumpData.GetStartForMetric (h => h.ReheatingStagesHeatQuantityHotWaterTotal),
                    ReheatingStagesHeatQuantityHotWaterTotalEnd = heatPumpData.GetEndForMetric (h => h.ReheatingStagesHeatQuantityHotWaterTotal),
                    ReheatingStagesHeatQuantityHotWaterTotalDelta = heatPumpData.GetDeltaForMetric (h => h.ReheatingStagesHeatQuantityHotWaterTotal),
                    PowerConsumptionHeatingDayStart = heatPumpData.GetStartForMetric (h => h.PowerConsumptionHeatingDay),
                    PowerConsumptionHeatingDayEnd = heatPumpData.GetEndForMetric (h => h.PowerConsumptionHeatingDay),
                    PowerConsumptionHeatingDayDelta = heatPumpData.GetDeltaForMetric (h => h.PowerConsumptionHeatingDay),
                    PowerConsumptionHeatingSumStart = heatPumpData.GetStartForMetric (h => h.PowerConsumptionHeatingSum),
                    PowerConsumptionHeatingSumEnd = heatPumpData.GetEndForMetric (h => h.PowerConsumptionHeatingSum),
                    PowerConsumptionHeatingSumDelta = heatPumpData.GetDeltaForMetric (h => h.PowerConsumptionHeatingSum),
                    PowerConsumptionHotWaterDayStart = heatPumpData.GetStartForMetric (h => h.PowerConsumptionHotWaterDay),
                    PowerConsumptionHotWaterDayEnd = heatPumpData.GetEndForMetric (h => h.PowerConsumptionHotWaterDay),
                    PowerConsumptionHotWaterDayDelta = heatPumpData.GetDeltaForMetric (h => h.PowerConsumptionHotWaterDay),
                    PowerConsumptionHotWaterSumStart = heatPumpData.GetStartForMetric (h => h.PowerConsumptionHotWaterSum),
                    PowerConsumptionHotWaterSumEnd = heatPumpData.GetEndForMetric (h => h.PowerConsumptionHotWaterSum),
                    PowerConsumptionHotWaterSumDelta = heatPumpData.GetDeltaForMetric (h => h.PowerConsumptionHotWaterSum),
                    RuntimeVaporizerHeatingStart = heatPumpData.GetStartForMetric (h => h.RuntimeVaporizerHeating),
                    RuntimeVaporizerHeatingEnd = heatPumpData.GetEndForMetric (h => h.RuntimeVaporizerHeating),
                    RuntimeVaporizerHeatingDelta = heatPumpData.GetDeltaForMetric (h => h.RuntimeVaporizerHeating),
                    RuntimeVaporizerHotWaterStart = heatPumpData.GetStartForMetric (h => h.RuntimeVaporizerHotWater),
                    RuntimeVaporizerHotWaterEnd = heatPumpData.GetEndForMetric (h => h.RuntimeVaporizerHotWater),
                    RuntimeVaporizerHotWaterDelta = heatPumpData.GetDeltaForMetric (h => h.RuntimeVaporizerHotWater),
                    RuntimeVaporizerDefrostStart = heatPumpData.GetStartForMetric (h => h.RuntimeVaporizerDefrost),
                    RuntimeVaporizerDefrostEnd = heatPumpData.GetEndForMetric (h => h.RuntimeVaporizerDefrost),
                    RuntimeVaporizerDefrostDelta = heatPumpData.GetDeltaForMetric (h => h.RuntimeVaporizerDefrost),
                    ReheatingStages1Start = heatPumpData.GetStartForMetric (h => h.ReheatingStages1),
                    ReheatingStages1End = heatPumpData.GetEndForMetric (h => h.ReheatingStages1),
                    ReheatingStages1Delta = heatPumpData.GetDeltaForMetric (h => h.ReheatingStages1),
                    ReheatingStages2Start = heatPumpData.GetStartForMetric (h => h.ReheatingStages2),
                    ReheatingStages2End = heatPumpData.GetEndForMetric (h => h.ReheatingStages2),
                    ReheatingStages2Delta = heatPumpData.GetDeltaForMetric (h => h.ReheatingStages2),
                    DefrostTimeStart = heatPumpData.GetStartForMetric (h => h.DefrostTime),
                    DefrostTimeEnd = heatPumpData.GetEndForMetric (h => h.DefrostTime),
                    DefrostTimeDelta = heatPumpData.GetDeltaForMetric (h => h.DefrostTime),
                    DefrostStartsStart = heatPumpData.GetStartForMetric (h => h.DefrostStarts),
                    DefrostStartsEnd = heatPumpData.GetEndForMetric (h => h.DefrostStarts),
                    DefrostStartsDelta = heatPumpData.GetDeltaForMetric (h => h.DefrostStarts),
                    Year = year,
                    PeriodKind = periodKind,
                    PeriodNumber = periodNumber.ToString (),
                    First = heatPumpData.GetFirst (),
                    Last = heatPumpData.GetLast (),
                    DateUpdated = now,
                    DateCreated = now
            };
        }
    }
}