using System.Collections.Generic;

namespace StiebelEltronApiServer.Services
{
    public static class Tags
    {
        public static readonly IDictionary<string, Tag> TagMap = new Dictionary<string, Tag>()
        {
          { "a", Tag.a },
          { "abbr", Tag.abbr },
          { "acronym", Tag.acronym },
          { "address", Tag.address },
          { "applet", Tag.applet },
          { "area", Tag.area },
          { "article", Tag.article },
          { "aside", Tag.aside },
          { "audio", Tag.audio },
          { "b", Tag.b },
          { "base", Tag.@base },
          { "basefont", Tag.basefont },
          { "bdo", Tag.bdo },
          { "big", Tag.big },
          { "blockquote", Tag.blockquote },
          { "body", Tag.body },
          { "br", Tag.br },
          { "button", Tag.button },
          { "canvas", Tag.canvas },
          { "caption", Tag.caption },
          { "center", Tag.center },
          { "cite", Tag.cite },
          { "code", Tag.code },
          { "col", Tag.col },
          { "colgroup", Tag.colgroup },
          { "datalist", Tag.datalist },
          { "dd", Tag.dd },
          { "del", Tag.del },
          { "dfn", Tag.dfn },
          { "div", Tag.div },
          { "dl", Tag.dl },
          { "dt", Tag.dt },
          { "em", Tag.em },
          { "embed", Tag.embed },
          { "fieldset", Tag.fieldset },
          { "figcaption", Tag.figcaption },
          { "figure", Tag.figure },
          { "font", Tag.font },
          { "footer", Tag.footer },
          { "form", Tag.form },
          { "frame", Tag.frame },
          { "frameset", Tag.frameset },
          { "head", Tag.head },
          { "header", Tag.header },
          { "h1",  Tag.h1 },
          { "h2", Tag.h2 },
          { "h3", Tag.h3 },
          { "h4", Tag.h4 },
          { "h5", Tag.h5 },
          { "h6", Tag.h6 },
          { "hr", Tag.hr },
          { "html", Tag.html },
          { "i", Tag.i },
          { "iframe", Tag.iframe },
          { "img", Tag.img },
          { "input", Tag.input },
          { "ins", Tag.ins },
          { "kbd", Tag.kbd },
          { "label", Tag.label },
          { "legend", Tag.legend },
          { "li", Tag.li },
          { "link", Tag.link },
          { "main", Tag.main },
          { "map", Tag.map },
          { "mark", Tag.mark },
          { "meta", Tag.meta },
          { "meter", Tag.meter },
          { "nav", Tag.nav },
          { "noscript", Tag.noscript },
          { "object", Tag.@object },
          { "ol", Tag.ol },
          { "optgroup", Tag.optgroup },
          { "option", Tag.option },
          { "p", Tag.p },
          { "param", Tag.param },
          { "pre", Tag.pre },
          { "progress", Tag.progress },
          { "q", Tag.q },
          { "s", Tag.s },
          { "samp", Tag.samp },
          { "script", Tag.script },
          { "section", Tag.section },
          { "select", Tag.select },
          { "small", Tag.small },
          { "source", Tag.source },
          { "span", Tag.span },
          { "strike", Tag.strike },
          { "strong", Tag.strong },
          { "style", Tag.style },
          { "sub", Tag.sub },
          { "sup", Tag.sup },
          { "table", Tag.table },
          { "tbody", Tag.tbody },
          { "td", Tag.td },
          { "textarea", Tag.textarea },
          { "tfoot", Tag.tfoot },
          { "th", Tag.th },
          { "thead", Tag.thead },
          { "time", Tag.time },
          { "title", Tag.title },
          { "tr", Tag.tr },
          { "u", Tag.u },
          { "ul", Tag.ul },
          { "var", Tag.var },
          { "video", Tag.video },
          { "wbr", Tag.wbr }, 
      };
      public record TagContext(string tag, string id);
      public enum Tag
        {
            a,
            abbr,
            acronym,
            address,
            applet,
            area,
            article,
            aside,
            audio,
            b,
            @base,
            basefont,
            bdo,
            big,
            blockquote,
            body,
            br,
            button,
            canvas,
            caption,
            center,
            cite,
            code,
            col,
            colgroup,
            datalist,
            dd,
            del,
            dfn,
            div,
            dl,
            dt,
            em,
            embed,
            fieldset,
            figcaption,
            figure,
            font,
            footer,
            form,
            frame,
            frameset,
            head,
            header,
            h1, h2, h3, h4, h5, h6,
            hr,
            html,
            i,
            iframe,
            img,
            input,
            ins,
            kbd,
            label,
            legend,
            li,
            link,
            main,
            map,
            mark,
            meta,
            meter,
            nav,
            noscript,
            @object,
            ol,
            optgroup,
            option,
            p,
            param,
            pre,
            progress,
            q,
            s,
            samp,
            script,
            section,
            select,
            small,
            source,
            span,
            strike,
            strong,
            style,
            sub,
            sup,
            table,
            tbody,
            td,
            textarea,
            tfoot,
            th,
            thead,
            time,
            title,
            tr,
            u,
            ul,
            var,
            video,
            wbr,
        }
    } 
}