version: "3.3"
services:
    web:
        build:
            context: .
        container_name: "dashboard"
        restart: always
        ports:
            - "80:6003"
            - "443:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw
            - ./data/logs:/app/logs
        environment:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            ConnectionStrings__DefaultConnection: "${DatabaseConnectionString}"
            ServiceWeltUrl: ${ServiceWeltUrl}
            ServiceWeltUser: ${ServiceWeltUser}
            ServiceWeltPassword: ${ServiceWeltPassword}
        depends_on:
            - db
    db:
        image: "postgres:latest"  # PostgreSQL wird verwendet, das auf ARM läuft
        container_name: "postgres"
        restart: always
        ports:
        - "5432:5432"
        volumes:
        - ./data/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DatabasePassword}  # Definiert das Passwort für den Postgres-Benutzer
