FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy@sha256:7c808ca379d3836044627a0bb5d4fc84520f41bca775706d37ca6863fea3567b AS build
ARG ConnectionString=default_connection_string
ENV ConnectionString=$ConnectionString
WORKDIR /app
COPY stiebel-eltron-dashboard.csproj .
RUN dotnet restore
COPY . .
RUN dotnet build stiebel-eltron-dashboard.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish stiebel-eltron-dashboard.csproj -c Release -o /app
FROM publish AS final
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:6003;https://+:6004
EXPOSE 6003 6004
WORKDIR /app

COPY --from=publish /app/entrypoint_dbmigrate.sh .
COPY --from=publish /app .
COPY --from=publish /app/etc/ssl/openssl.cnf /etc/ssl/openssl.cnf

ENTRYPOINT bash ./entrypoint_dbmigrate.sh ${ConnectionString}
