version: "3.3"
services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};" 
                ServiceWeltUser: "${ServiceWeltUser}"
                ServiceWeltPassword: "${ServiceWeltPassword}"
                ServiceWeltUrl: "${ServiceWeltUrl}"
            context: .
        container_name: "dashboard"
        ports:
            - "80:6003"
            - "443:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw
            - ./data/logs:/app/logs
        environment:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/azure-sql-edge:1.0.5"
        user: root
        container_name: "mssql"
        restart: always
        cap_add:
            - SYS_PTRACE
        ports:
            - "1433:1433"
        volumes:
            - ./data/mssql/data/:/var/opt/mssql/data
        environment:
            MSSQL_SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: 1
            MSSQL_PID: Developer
