services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};"
                ServiceWeltUser: "${ServiceWeltUser}"
                ServiceWeltPassword: "${ServiceWeltPassword}"
                ServiceWeltUrl: "${ServiceWeltUrl}"
            context: .
            dockerfile: Dockerfile_DbMigrate
        container_name: "migration"
        ports:
            - "${HttpPort}:6003"
            - "${HttpsPort}:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw    
            - ./Data/Migrations:/app/Data/Migrations:rw          
        depends_on:
            - db
    db:
        image: "postgres:latest"  # PostgreSQL wird verwendet, das auf ARM läuft
        container_name: "postgres"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DatabasePassword}  # Definiert das Passwort für den Postgres-Benutzer

