services:
    web:
        build:
            context: .
        container_name: "dashboard"
        restart: always
        ports:
            - "${HttpPort}:6003"
            - "${HttpsPort}:6004"
        volumes:
            - ./web/root/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys:rw
            - ./data/logs:/app/logs
        environment:
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            ConnectionStrings__DefaultConnection: "${DatabaseConnectionString}"
            ServiceWeltUrl: ${ServiceWeltUrl}
            ServiceWeltUser: ${ServiceWeltUser}
            ServiceWeltPassword: ${ServiceWeltPassword}
        depends_on:
            - db
    db:
        image: "postgres:16.3"  # PostgreSQL wird verwendet, das auf ARM läuft
        container_name: "postgres"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: sa                       # Benutzer 'sa' fest definiert
            POSTGRES_PASSWORD: ${DatabasePassword}  # Passwort für den Benutzer 'sa'
    db_upgrade:
        image: postgres:17
        container_name: "pg_upgrade"
        volumes:
            - ./data/postgres:/var/lib/postgresql/16/data
            - ./data/postgres_new:/var/lib/postgresql/17/data
            - ./upgrade_pg.sh:/upgrade_pg.sh
        entrypoint: ["/bin/bash", "/upgrade_pg.sh"]
        user: "root"  # <-- PostgreSQL läuft als postgres-Benutzer
        depends_on:
            - db

