services:
    web:
        build:
            args:
                ConnectionString: "${DatabaseConnectionString};"
                ServiceWeltUser: "${ServiceWeltUser}"
                ServiceWeltPassword: "${ServiceWeltPassword}"
                ServiceWeltUrl: "${ServiceWeltUrl}"
            context: .
            dockerfile: Dockerfile_DbScaffold
        container_name: "dashboard"             
        volumes:
            - ./Data/Generated:/app/DbModels:rw       
        depends_on:
            - db             
    db:
        image: "mcr.microsoft.com/azure-sql-edge:1.0.5"
        user: root        
        container_name: "mssql"
        restart: always      
        ports:
            - "1433:1433"       
        volumes:
            - ./data/mssql/data/:/var/opt/mssql/data
        environment:
            MSSQL_SA_PASSWORD: ${DatabasePassword}
            ACCEPT_EULA: 1
            MSSQL_PID: Developer
